classDiagram
    class ProductGroup {
        <<credentialSubject>>
        versionsOfStandards
        railProfile
        steelGrade
    }

    class Transport {
        <<credentialSubject>>
        serviceProviderId
        timeDeparture
        timeArrival
        globalWarmingPotentialTransport
    }

    class TransportBatch {
        <<credentialSubject>>
        locationDeparture
        locationArrival
    }

    class DPP {
        <<credentialSubject>>
        productId
        name
        granularity
        facilityId
        length
        weight
    }

    class EU-DPP-Registry {
        <<registry>>
        dppRegistrationNumber
    }

    class DppSchema {
        <<dictonary>>
        version
        templateName
    }
    class DoPC {
        <<credentialSubject>>
        deglerationOfProductConformity
    }

    class EPD {
        <<credentialSubject>>
        globalWarmingPotential
    }

    class MeansOfTransport {
        <<credentialSubject>>
        typeOfTransport        

    }

    EPD "1" --> "0..n" TransportType: epdSubjectId
    Transport "0..n" --> "1" TransportType: transportTypeId
    Transport "0..n" --> "1" TransportBatch: transportBatchId
    DPP "1..n" <-- "0..n" TransportBatch: dppId
    DPP "0..n" <-- "0..1" EU-DPP-Registry: dppId
    DPP "0..n" --> "1" ProductGroup: productGroupId
    ProductGroup "1..n" <-- "1" EPD: epdSubjectId
    EPD "1..n" <-- "0..1" DoPC: epdId
    DppSchema "1" --> "0..n" DPP: dppSchemaID
